### ISSUE TITLE
undefined reference to `__intrinsic_setjmpex'

### ISSUE THREAD

**Issue by mvasi90** [pwiecz/go-fltk#125]
Impossible to build from Linux to Windows binary:

```
/usr/lib/go/pkg/tool/linux_amd64/link: running x86_64-w64-mingw32-g++ failed: exit status 1
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: /home/developer/go/src/github.com/pwiecz/go-fltk/lib/windows/amd64/libfltk_images.a(Fl_JPEG_Image.cxx.obj):Fl_JPEG_Image.:(.text+0x1b8): undefined reference to `__intrinsic_setjmpex'
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: /home/developer/go/src/github.com/pwiecz/go-fltk/lib/windows/amd64/libfltk_images.a(Fl_PNG_Image.cxx.obj):Fl_PNG_Image.c:(.text+0x133): undefined reference to `__intrinsic_setjmpex'
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: /home/developer/go/src/github.com/pwiecz/go-fltk/lib/windows/amd64/libfltk_png.a(png.c.obj):png.c:(.text+0x1367): undefined reference to `__intrinsic_setjmpex'
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: /home/developer/go/src/github.com/pwiecz/go-fltk/lib/windows/amd64/libfltk_png.a(pngerror.c.obj):pngerror.c:(.text+0xbd5): undefined reference to `__intrinsic_setjmpex'
/usr/lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/bin/ld: /home/developer/go/src/github.com/pwiecz/go-fltk/lib/windows/amd64/libfltk_png.a(pngerror.c.obj):pngerror.c:(.text+0x13ea): undefined reference to `__intrinsic_setjmpex'
collect2: error: ld returned 1 exit status
```

**Comment by MoAlyousef** [comment]
I think it's because the CI prebuilt libs are built against ucrt, whereas the mingw toolchain on linux uses msvcrt.

**Comment by zivlamp** [comment]
I had the same problem when I upgraded the dependencies in go.mod to v0.0.0-20240129144424-3260f5ba37f1.

**Comment by pwiecz** [comment]
@zivlamp I'll be looking into it, but most likely next week.

**Comment by zivlamp** [comment]
Thanks for reply.
 Additional note: It's no problem in Linux, and it compiles fine in windows with gio version 20221204.

**Comment by zivlamp** [comment]
I switched the version to the latest in go.mod.
It's working now! Thanks for your work and suggestions!
